name: spotify_clone
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.5.4


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.17
  palette_generator: ^0.3.3
  just_audio: ^0.9.36
  firebase_core: ^2.27.0
  firebase_storage: ^11.6.7
  firebase_auth: ^4.17.8
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0


flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/audio/songs/
    - assets/images/1st row/
    - assets/images/2nd row/
    - assets/images/3rd row/
    - assets/images/bts songs/
    - assets/images/kpop/
    - assets/images/kdrama/
    - assets/images/hindi/
    - assets/images/disney/
    - assets/images/wedding/
    - assets/images/comfort/
    - assets/images/trending/
    - assets/images/sleep/
    - assets/images/love/
    - assets/logo/
    - assets/svg/
    - assets/png/


  # example:
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Black.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
